language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
# command to install dependencies  
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coverage
  - pip install python-coveralls
  - pip install pytest-cov
before script:
  - ls
# command to run tests
script:
  - pytest --cov-report term --cov-report xml --cov=bt_expense tests/
after_success:
  - coveralls
  - ls
branches:
  only:
    - master
    - dev