env:
  global:
    - CC_TEST_REPORTER_ID=6ea71d63c94102cdc54e78a76a58e3803e36f5247d1ba4cc04a1ed9af2e5623b
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7-dev"
# command to install dependencies  
install:
  - pip install --upgrade pip 
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coverage
  - pip install python-coveralls
  - pip install pytest-cov
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
# command to run tests
script:
  - pwd
  - ls
  - pytest -v --cov-report term --cov-report xml --cov=bt_expense tests/
after_script:
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
after_success:
  - coveralls
branches:
  only:
    - master
    - dev